### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by justusbunsi** [forgeqc/sonarqube-api-client#5]
Hi @matt6697, I stumbled across this repository while searching for client implementations of the SonarQube API. It's pretty intuitive to use but I've noticed there are no changes in the last 2 years. What is the status of the project? Do you still maintain it? 

In your [contribution section](https://github.com/forgeqc/sonarqube-api-client#contributing) you've mentioned that the `official API is not part of this project`. Does this mean there are no plans to implement a client fully covering the API?

Do you need help to update the client to match the current API? 

Happy to hear from you.

**Comment by matt6697** [comment]
Not a lot of time to maintain it but feel free to provide a pull request to comply with the latest version of  the Sonarqube API if some parts of the code are deprecated.

I agree that the contribution section is not very clear ;-)

**Comment by justusbunsi** [comment]
Thanks for your reply. I'll have a closer look and provide PRs, when there are useful additions.
